=== 13927729580/knime-core/de.unikn.knime.core/src/de/unikn/knime/core/node/Node.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT knimeNode ( name, shortDescription, fullDescription, ports, views? ) >
<!ATTLIST knimeNode icon CDATA #IMPLIED>

<!ELEMENT name (#PCDATA) >
<!ELEMENT shortDescription (#PCDATA) >

<!ELEMENT fullDescription (intro, option*) >
<!ELEMENT intro (#PCDATA | p | h | br | b | i | u | a)* >
<!ELEMENT option (#PCDATA | p | h | br | b | i | u | a)* >
<!ATTLIST option name CDATA #REQUIRED>

<!ELEMENT p (#PCDATA | br | b | i | u | a)* >
<!ELEMENT h (#PCDATA) >
<!ELEMENT b (#PCDATA) >
<!ELEMENT i (#PCDATA) >
<!ELEMENT u (#PCDATA) >
<!ELEMENT a (#PCDATA) >
<!ATTLIST a href CDATA #REQUIRED>

<!ELEMENT ports (dataIn*, dataOut*, predParamIn*, predParamOut*) >
<!ELEMENT dataIn (#PCDATA) >
<!ATTLIST dataIn index CDATA #REQUIRED>
<!ATTLIST dataIn name CDATA #IMPLIED>
<!ELEMENT dataOut (#PCDATA) >
<!ATTLIST dataOut index CDATA #REQUIRED>
<!ATTLIST dataOut name CDATA #IMPLIED>
<!ELEMENT predParamIn (#PCDATA) >
<!ATTLIST predParamIn index CDATA #REQUIRED>
<!ATTLIST predParamIn name CDATA #IMPLIED>
<!ELEMENT predParamOut (#PCDATA) >
<!ATTLIST predParamOut index CDATA #REQUIRED>
<!ATTLIST predParamOut name CDATA #IMPLIED>

<!ELEMENT views (view+) >
<!ELEMENT view (#PCDATA) >
<!ATTLIST view index CDATA #REQUIRED>
<!ATTLIST view name CDATA #REQUIRED>

=== 13927729580/knime-core/org.knime.timeseries/src/org/knime/timeseries/node/Segmentation/TSBetweenEvents/TSBetweenEventsNodeFactory.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE knimeNode PUBLIC "-//UNIKN//DTD KNIME Node 2.0//EN" "http://www.knime.org/Node.dtd">
<knimeNode type="Manipulator" icon="time_events.png">
    <name>Time Series between events</name>
    <shortDescription>Extracts time series between events 
    (represented as strings) in an apposite column.
    </shortDescription>
    <fullDescription>
        <intro>
            Extracts time series from the input table located between 
            string "xxxx", where xxxx is the name of the event 
            (for example "split").
        </intro>
        <option name="Columns containing event strings">
        Select the input column containing the name of the event where you
        to split the original time series.</option>
        <option name="String Event">
        Name of the events where to split the original time series.</option>
        <option name="Date for output table">
        Output table will be the one conatining data from this date</option>
        <option name="Date Format">
        Date format for previous parameter</option>
        <option name="timestamp column name">
        Name of colun containing timestamp data</option>
    </fullDescription>
    <ports>
        <dataIn index="0" name="Input column">
        Table containing string event column.</dataIn>
        <dataOut index="0" name="Wrapped output">
        Table containing the time series between event i 
        and event i+1 and date as specified in dialog panel.</dataOut>
    </ports>
</knimeNode>

=== 13927729580/knime-core/org.knime.timeseries/src/org/knime/timeseries/node/fuzzyCPmeans/FuzzyClusterPearsonNodeFactory.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE knimeNode PUBLIC "-//UNIKN//DTD KNIME Node 1.0//EN" "http://www.knime.org/Node.dtd">
<knimeNode icon="./kmeans.ico" type = "Learner">
	<name>Fuzzy c-Pearson-Means</name>
	<shortDescription>
	    Performs fuzzy c-means clustering using Pearson Coefficient.
	</shortDescription>
	
	<fullDescription>
		<intro>		
		<p>
		under construction...
		</p>
	</intro>
	<option name="Number of clusters">
	Number of clusters to use for the algorithm.
    </option>
    <option name="Maximum number of iterations">
    This is the maximum number of iterations to be performed.
    </option>
    <option name="Fuzzifier">
    Indicates how much the clusters are allowed to overlap.
    </option>
    <option name="Induce noise cluster">
    Whether to induce a noise cluster or not.
    </option>
     <option name="Set delta">
    Delta is the fixed distance from every datapoint to the noise cluster.
    </option>
    <option name="Set delta automatically, specify lambda">
    Delta is updated in each iteration, based on the average interpoint 
    distances. However, a lambda paramater has to be set, according to the
    shape of the clusters.
    </option>
    <option name="Perform the clustering in memory">
    If this option is selected, the clustering is performed in the memory,
    which speeds up the process.
    </option>
    <option name="Compute cluster quality measures">
    Whether to calculate quality measures for the clustering. This can be
    time and memory consuming with large datasets.
    </option>
	</fullDescription>
	
	<ports>
		<dataIn index="0" name="Training data">Datatable with training data. Make
		sure that the data are normalized!</dataIn>
		<dataOut index="0" name="Cluster Memberships">Input table extended
		 by cluster membership</dataOut>
		<modelOut index="0" name="Prototypes">Cluster centers</modelOut>
	</ports>
	<views>
		<view index="0" name="Statistics View">
			Shows the WithinClusterVariation and the BetweenClusterVariation, 
			which are indicators for 'good' clustering.
		</view>
	</views>	
</knimeNode>

=== 13927729580/knime-core/org.knime.timeseries/src/org/knime/timeseries/node/extract/TimeFieldExtractorNodeFactory.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE knimeNode PUBLIC "-//UNIKN//DTD KNIME Node 2.0//EN" "http://www.knime.org/Node.dtd">
<knimeNode type="Manipulator" icon="time_field_extractor.png">
    <name>Time Field Extractor</name>
    <shortDescription>Extracts time fields such as year, month, hour, minute
    from a timestamp and appends the value as integer columns.
    </shortDescription>
    <fullDescription>
        <intro>
            Extracts the selected time fields from a timestamp column and
            appends the values as integer columns. Valid fields are year, month,
            day, hour, minute, second and millisecond. If the values are not 
            set in the timestamp a missing value is added in the 
            result table.    
        </intro>
        <option name="Column containing timestamps">
        Select the input column containing date/time stamps.</option>
        <option name="Year">Check if the year should be extracted and appended 
        as an integer column. The name for this column can be specified.
        </option>
        <option name="Quarter">Check if the quarter as a number in [1,4] should 
        be extracted and appended as an integer column. 
        The name for this column can be specified.
        </option>        
        <option name="Month">Check if the month should be extracted and appended 
        as an integer column. The name for this column can be specified.
        </option>
        <option name="Month as">Select whether the (English) name of the month
        should be appended to the output table or the number of the month in 
        [1, 12].</option>
        <option name="Day">Check if the day of month should be extracted and 
        appended as an integer column. 
        The name for this column can be specified.
        </option>
        <option name="Hour">Check if the hour of day should be extracted and 
        appended as an integer column. 
        The name for this column can be specified.
        </option>
        <option name="Minute">Check if the minute should be extracted and appended 
        as an integer column. The name for this column can be specified.
        </option>
        <option name="Second">Check if the second should be extracted and appended 
        as an integer column. The name for this column can be specified.
        </option>           
        <option name="Millisecond">Check if the millisecond should be extracted 
        and appended as an integer column. 
        The name for this column can be specified.
        </option>             
    </fullDescription>
    <ports>
        <inPort index="0" name="Input column">
        Table containing timestamp cells.</inPort>
        <outPort index="0" name="Extracted time fields">
        Input table with extracted time fields appended</outPort>
    </ports>
</knimeNode>

=== 13927729580/knime-core/org.knime.timeseries/src/org/knime/dev/node/timeseries/Segmentation/ExtractFromTo/ExtractFromToNodeFactory.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE knimeNode PUBLIC "-//UNIKN//DTD KNIME Node 1.0//EN" "http://www.knime.org/Node.dtd">
<knimeNode type="Manipulator" icon="">
    <name>Extract From To</name>
    <shortDescription>Extracts data from Timestamp1 to Timestamp2 from input table.
    </shortDescription>
    <fullDescription>
        <intro>
            Extracts from input table a sub-table with data 
            between TimeStamp1 and Timestamp2.
        </intro>
        <option name="Columns containing Timestamp">
        Select the input column containing timestamp cells.</option>
        <option name="From: Timestamp">
        First Timestamp boundary of the extraction interval.</option>
        <option name="To: Timestamp">
        Second Timestamp boundary of the extraction interval.</option>
    </fullDescription>
    <ports>
        <dataIn index="0" name="Input column">
        Table containing timestamp cells.</dataIn>
        <dataOut index="0" name="Wrapped output">
        Sub-Table containing only data between "From: Timestamp" and 
        "To: Timestamp".</dataOut>
    </ports>
</knimeNode>

=== 13927729580/knime-core/org.knime.timeseries/src/org/knime/timeseries/node/Segmentation/OneSampleperDay/OneSampleperDayNodeFactory.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE knimeNode PUBLIC "-//UNIKN//DTD KNIME Node 2.0//EN" "http://www.knime.org/Node.dtd">
<knimeNode type="Manipulator" icon="time_per_day.png">
    <name>One Sample per Day</name>
    <shortDescription>Extracts one row per each day from input table.
    </shortDescription>
    <fullDescription>
        <intro>
            Extracts one row of values per day at a fixed time of day.
        </intro>
        <option name="Columns containing Timestamp">
        Select the input column containing timestamp cells.</option>
        <option name="At: Timestamp">
        Timestamp to use to extract one value per day.</option>
    </fullDescription>
    <ports>
        <dataIn index="0" name="Input column">
        Table containing timestamp cells.</dataIn>
        <dataOut index="0" name="Wrapped output">
        Sub-Table containing only data extracted at 
        "At: Timestamp" each day.</dataOut>
    </ports>
</knimeNode>

=== 13927729580/knime-core/org.knime.base/src/org/knime/base/node/meta/feature/selection/FeatureSelectionLoopEndNodeFactory.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE knimeNode PUBLIC "-//UNIKN//DTD KNIME Node 2.0//EN" "http://www.knime.org/Node.dtd">
<knimeNode icon="feature_elimination_loop_end.png" type="LoopEnd">
	<name>Feature Selection Loop End</name>

	<shortDescription>End node for a feature selection loop</shortDescription>

	<fullDescription>
		<intro>
			This is the end of a feature selection loop which selects
			features
			according to a feature selection strategy.
		</intro>

		<option name="Score variable">The flow variable that contains the score for the
			model
		</option>
		<option name="Minimize">Check if the score should be minimized (for
			example if you use the classification error as score)
		</option>
	</fullDescription>

	<ports>
		<inPort index="0"
			name="FlowVariable connection containing the score variable">FlowVariable connection that contains the variable you want to
			use as score.
		</inPort>
		<outPort index="0" name="Feature Selection Model">A model that represents the different
			column selections with the associated scores.
		</outPort>
	</ports>
</knimeNode>
