=== 13927729580/knime-core/de.unikn.knime.core/src/de/unikn/knime/core/node/Node.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT knimeNode ( name, shortDescription, fullDescription, ports, views? ) >
<!ATTLIST knimeNode icon CDATA #IMPLIED>

<!ELEMENT name (#PCDATA) >
<!ELEMENT shortDescription (#PCDATA) >

<!ELEMENT fullDescription (intro, option*) >
<!ELEMENT intro (#PCDATA | p | h | br | b | i | u | a)* >
<!ELEMENT option (#PCDATA | p | h | br | b | i | u | a)* >
<!ATTLIST option name CDATA #REQUIRED>

<!ELEMENT p (#PCDATA | br | b | i | u | a)* >
<!ELEMENT h (#PCDATA) >
<!ELEMENT b (#PCDATA) >
<!ELEMENT i (#PCDATA) >
<!ELEMENT u (#PCDATA) >
<!ELEMENT a (#PCDATA) >
<!ATTLIST a href CDATA #REQUIRED>

<!ELEMENT ports (dataIn*, dataOut*, predParamIn*, predParamOut*) >
<!ELEMENT dataIn (#PCDATA) >
<!ATTLIST dataIn index CDATA #REQUIRED>
<!ATTLIST dataIn name CDATA #IMPLIED>
<!ELEMENT dataOut (#PCDATA) >
<!ATTLIST dataOut index CDATA #REQUIRED>
<!ATTLIST dataOut name CDATA #IMPLIED>
<!ELEMENT predParamIn (#PCDATA) >
<!ATTLIST predParamIn index CDATA #REQUIRED>
<!ATTLIST predParamIn name CDATA #IMPLIED>
<!ELEMENT predParamOut (#PCDATA) >
<!ATTLIST predParamOut index CDATA #REQUIRED>
<!ATTLIST predParamOut name CDATA #IMPLIED>

<!ELEMENT views (view+) >
<!ELEMENT view (#PCDATA) >
<!ATTLIST view index CDATA #REQUIRED>
<!ATTLIST view name CDATA #REQUIRED>

=== 13927729580/knime-core/org.knime.timeseries/src/org/knime/timeseries/node/MA/MovingAverageNodeFactory.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE knimeNode PUBLIC "-//UNIKN//DTD KNIME Node 1.0//EN" "http://www.knime.org/Node.dtd">
<knimeNode type="Manipulator" icon="moving_avg.png">
    <name>Moving Average</name>
    <shortDescription>Adds a column with moving average values.</shortDescription>
    <fullDescription>
        <intro>
            This node calculates the moving average of a column.
            The moving average values are displayed in a new column appended 
            at the end of the table.
        </intro>
        <option name="Columns containing Double Values">
        Select the input column containing double values on which to
        perform the moving average.</option>
        <option name="Type of Moving Average"> Moving Average can be simple 
         or exponential (used in financial analysis).
        </option>
        <option name="Window Length"> The number of samples to include in 
        the moving average window. It has to be an odd number. 
        Minimum value: 3 samples. Maximum Value: Time Series length.
        </option>
    </fullDescription>
    <ports>
        <dataIn index="0" name="Input column">
        Table containing time series.</dataIn>
        <dataOut index="0" name="Wrapped output">
        Table with appended column holding moving average values.</dataOut>
    </ports>
</knimeNode>

=== 13927729580/knime-core/org.knime.timeseries/src/org/knime/timeseries/node/dateshift/DateShiftNodeFactory.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE knimeNode PUBLIC "-//UNIKN//DTD KNIME Node 2.0//EN" "http://www.knime.org/Node.dtd">
<knimeNode type="Manipulator" icon="dateshift.png">
    <name>Date/Time Shift </name>
    
    <shortDescription>
        Adds a value as defined in a numerical column in a defined granularity to an existing date.
    </shortDescription>
    
    <fullDescription>
        <intro> This node adds the value of a numerical column to an existing date. This value can represent different
        aspects of the date, as defined by its aggregation level 
        (year, quarter, month, week, day, hour, minute).
        
        There are different possibilities for selecting a date. The first possibility is the execution time, which will 
        produce a different result in each run. The second one, is a date and time column. It is also possible to enter 
        a fixed date in the dialog or to use the 1.1.1970, which is the default zero in Unix applications.
        </intro>
        
        <option name="Select value column">Select the column containing the value to apply.</option>
        <option name="Select a date column">Select a column containing a date</option>
        <option name="Fixed time">Select a fixed time.</option>   
        <option name="Select granularity of value">The granularity of the numerical column 
        	(in years, quarters, months, weeks, days, hours, minutes)</option>
        <option name="Appended column name">Name of the newly appended column containing the calculate date/time. </option>  
        <option name="Fixed time">The fixed time for the corresponding option. </option>  
        <option name="Use date">Check for using the date in the output date column. </option>      
        <option name="Use time">Check for using the time in the output date column. </option>      
        <option name="Use miliseconds">Check for using the miliseconds in the output date column. </option>                              
    </fullDescription>
    
    <ports>
        <inPort index="0" name="Table with date information">In data with at least one numerical column</inPort>
        <outPort index="0" name="Date">Out data with the calculated date appended</outPort>
    </ports>    
</knimeNode>

=== 13927729580/knime-core/org.knime.timeseries/src/org/knime/timeseries/node/filter/extract/ExtractTimeWindowNodeFactory.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE knimeNode PUBLIC "-//UNIKN//DTD KNIME Node 2.0//EN" "http://www.knime.org/Node.dtd">
<knimeNode type="Manipulator" icon="extract_time_window.png">
    <name>Extract Time Window</name>
    <shortDescription>Extracts all rows with a time stamp within the specified
      time window.
    </shortDescription>
    <fullDescription>
        <intro>
            Extracts from input table a sub-table with data 
            between TimeStamp1 and Timestamp2.
        </intro>
        <option name="Columns containing Timestamp">
        Select the input column containing timestamps.</option>
        <option name="From: Timestamp">
        Start date/time of the time window.</option>
        <option name="To: Timestamp">
        End date/time of the time window.</option>
    </fullDescription>
    <ports>
        <inPort index="0" name="Input column">
        Table containing timestamp cells.</inPort>
        <outPort index="0" name="Wrapped output">
        Sub-Table containing only data within time window.</outPort>
    </ports>
</knimeNode>

=== 13927729580/knime-core/org.knime.timeseries/src/org/knime/timeseries/node/generator/DateGeneratorNodeFactory.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE knimeNode PUBLIC "-//UNIKN//DTD KNIME Node 1.0//EN" "http://www.knime.org/Node.dtd">
<knimeNode  type="Source">
    <name>Time Generator</name>
    
    <shortDescription>
        Generates time values
    </shortDescription>
    
    <fullDescription>
        <intro>Generates time values with a certain number of equidistant 
        entries and within a configurable time period.</intro>
        
        
        <option name="Number of rows">How many rows should be generated</option>  
        <option name="Choose granularity level">Starting point of the time period</option>        
        <option name="Appended column name">End point of the time series</option>        
    </fullDescription>
    
    <ports>
        <dataOut index="0" name="Generated date">One column with the generated time</dataOut>
    </ports>    
</knimeNode>

=== 13927729580/knime-core/org.knime.timeseries/src/org/knime/timeseries/node/FilterWindows/FilterWindowsNodeFactory.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE knimeNode PUBLIC "-//UNIKN//DTD KNIME Node 2.0//EN" "http://www.knime.org/Node.dtd">
<knimeNode type="Manipulator" icon="moving_avg.png">
    <name>Moving Average</name>
    <shortDescription>Adds a column with moving average values.</shortDescription>
    <fullDescription>
        <intro>
            This node calculates the moving average of a column.
            The moving average values are displayed in a new column appended 
            at the end of the table.
        </intro>
        <option name="Columns containing Double Values">
        Select the input column containing double values on which to
        perform the moving average.</option>
    </fullDescription>
    <ports>
        <dataIn index="0" name="Input column">
        Table containing time series.</dataIn>
        <dataOut index="0" name="Wrapped output">
        Table with appended column holding moving average values.</dataOut>
    </ports>
</knimeNode>

=== 13927729580/knime-core/org.knime.timeseries/src/org/knime/timeseries/node/diff/TimeDifferenceNodeFactory.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE knimeNode PUBLIC "-//UNIKN//DTD KNIME Node 2.0//EN" "http://www.knime.org/Node.dtd">
<knimeNode type="Manipulator" icon="time_difference.png">
    <name>Time Difference</name>
    
    <shortDescription>
        Appends the difference between two dates.
    </shortDescription>
    
    <fullDescription>
        <intro>Appends the difference between two dates with the selected aggregation level 
        (year, quarter, month, week, day, hour, minute) and a selected precision for rounding.
        </intro>
        
        <option name="Select first date column">Select the column containing the start date</option>
        <option name="Select second date column">Select the column containing the end date</option>
        <option name="Select granularity of time difference">The granularity of the difference 
        	(in years, quarters, months, weeks, days, hours, minutes)</option>
        <option name="Rounding mode">How many fraction digits</option>
        <option name="Appended column name">Name of the newly appended column containing the time difference</option>                                
    </fullDescription>
    
    <ports>
        <inPort index="0" name="2 date columns">In data with at least two date columns</inPort>
        <outPort index="0" name="Difference">Out data with the time difference appended</outPort>
    </ports>    
</knimeNode>

=== 13927729580/knime-core/org.knime.timeseries/src/org/knime/timeseries/aggregate/TimeAggregatorNodeFactory.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE knimeNode PUBLIC "-//UNIKN//DTD KNIME Node 1.0//EN" "http://www.knime.org/Node.dtd">
<knimeNode  type="Manipulator">
    <name>Time Aggregator</name>
    
    <shortDescription>
        Aggregates the time to a higher aggregation level (e.g. month to quarter).
    </shortDescription>
    
    <fullDescription>
        <intro>Takes the time values from a column, aggregates it to a higher 
        granularity level (e.g. from month to quarter, etc.) and appends the 
        result as a string column.</intro>
        
        
        <option name="Select time column">Select the column containing the time that should be aggregated</option>	
        <option name="Choose granularity level">Choose aggregation level (year, quarter, month, week, day)</option>        
        <option name="Appended column name">The name of the new column</option>        
    </fullDescription>
    
    <ports>
        <dataIn index="0" name="Date column">In data with at least one date column</dataIn>
        <dataOut index="0" name="Aggregated date">In data with the aggregated time column appended</dataOut>
    </ports>    
</knimeNode>

=== 13927729580/knime-core/org.knime.timeseries/src/org/knime/timeseries/node/Segmentation/PatternsBetweenEvents/PatternsBetweenEventsNodeFactory.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE knimeNode PUBLIC "-//UNIKN//DTD KNIME Node 2.0//EN" "http://www.knime.org/Node.dtd">
<knimeNode type="Manipulator" icon="time_patterns.png">
    <name>Patterns between events</name>
    <shortDescription>Extracts patterns between events 
    (events represented as strings) in an apposite column.
    </shortDescription>
    <fullDescription>
        <intro>
            Extracts patterns from the input table located between 
            string "xxxx", where xxxx is the name of the event 
            (for example "split").
        </intro>
        <option name="Columns containing event strings">
        Select the input column containing the name of the event where you
        to split the original time series.</option>
        <option name="String Event">
        Name of the events where to split the original time series.</option>
        <option name="Column to generate output from">
        Name of the column from which patterns will be extracted.</option>
    </fullDescription>
    <ports>
        <dataIn index="0" name="Input column">
        Table containing string event column.</dataIn>
        <dataOut index="0" name="Wrapped output">
        Table containing new patterns.</dataOut>
    </ports>
</knimeNode>
