=== 13927729580/knime-core/org.knime.core/src/org/knime/core/node/Node.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!--
===============================================================================
 * This source code, its documentation and all appendant files
 * are protected by copyright law. All rights reserved.
 *
 * Copyright, 2003 - 2006
 * University of Konstanz, Germany.
 * Chair for Bioinformatics and Information Mining
 * Prof. Dr. Michael R. Berthold
 *
 * You may not modify, publish, transmit, transfer or sell, reproduce,
 * create derivative works from, distribute, perform, display, or in
 * any way exploit any of the content, in whole or in part, except as
 * otherwise expressly permitted in writing by the copyright owner or
 * as specified in the license file distributed with this product.
 *
 * If you have any questions please contact the copyright holder:
 * website: www.knime.org
 * email: contact@knime.org
===============================================================================
-->
<!ELEMENT knimeNode ( name, shortDescription, fullDescription, ports, views? ) >
<!ATTLIST knimeNode icon CDATA #IMPLIED>
<!ATTLIST knimeNode type (Source|Sink|Learner|Predictor|Manipulator|Visualizer|Meta|Other|Unknown) "Unknown">

<!ELEMENT name (#PCDATA) >
<!ELEMENT shortDescription (#PCDATA) >

<!ELEMENT fullDescription (intro, option*) >
<!ELEMENT intro (#PCDATA | p | h | br | b | i | u | a | ul | ol)* >
<!ELEMENT option (#PCDATA | p | h | br | b | i | u | a)* >
<!ATTLIST option name CDATA #REQUIRED>

<!ELEMENT p (#PCDATA | br | b | i | u | a | tt | ul | ol)* >
<!ELEMENT ul (li)+ >
<!ELEMENT ol (li)+ >
<!ELEMENT li (#PCDATA) >
<!ELEMENT h (#PCDATA) >
<!ELEMENT b (#PCDATA) >
<!ELEMENT i (#PCDATA) >
<!ELEMENT u (#PCDATA) >
<!ELEMENT a (#PCDATA) >
<!ELEMENT tt (#PCDATA) >
<!ELEMENT br EMPTY >
<!ATTLIST a href CDATA #REQUIRED>

<!ELEMENT ports (dataIn*, dataOut*, predParamIn*, predParamOut*) >
<!ELEMENT dataIn (#PCDATA) >
<!ATTLIST dataIn index CDATA #REQUIRED>
<!ATTLIST dataIn name CDATA #REQUIRED>
<!ELEMENT dataOut (#PCDATA) >
<!ATTLIST dataOut index CDATA #REQUIRED>
<!ATTLIST dataOut name CDATA #REQUIRED>
<!ELEMENT predParamIn (#PCDATA) >
<!ATTLIST predParamIn index CDATA #REQUIRED>
<!ATTLIST predParamIn name CDATA #REQUIRED>
<!ATTLIST predParamIn type CDATA "default">
<!ELEMENT predParamOut (#PCDATA) >
<!ATTLIST predParamOut index CDATA #REQUIRED>
<!ATTLIST predParamOut name CDATA #REQUIRED>
<!ATTLIST predParamOut type CDATA "default">

<!ELEMENT views (view+) >
<!ELEMENT view (#PCDATA) >
<!ATTLIST view index CDATA #REQUIRED>
<!ATTLIST view name CDATA #REQUIRED>

=== 13927729580/knime-core/org.knime.core/src/org/knime/core/node/workflow/virtual/parallelchunkstart/ParallelChunkStartNodeFactory.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE knimeNode PUBLIC "-//UNIKN//DTD KNIME Node 2.0//EN" "http://www.knime.org/Node.dtd">
<knimeNode icon="./parallelChunkStart.png" type="LoopStart">
    <name>Parallel Chunk Start</name>
    <shortDescription>Represents the start of a parallel chunked flow.</shortDescription>
    <fullDescription>
    <intro>
    Represents the start of a parallel chunked flow. Upon execution, it splits
    the input data into equally sized chunks and executes the body (terminated
    by the Parallel Chunk End) in parallel, each processing one chunk. The
    chunk count can be customized in the configuration dialog.
    </intro>
    <option name="Use automatic chunk count">
      Use a chunk count derived from the system's processor count.
    </option>
    <option name="Use custom chunk count">
      Specify the chunk count in the spinner.
    </option>
    </fullDescription>
    <ports>
        <inPort index="0" name="Input Data">
            The input data, split into chunks by the node.
        </inPort>
        <outPort index="0" name="Chunked Data">
            A representation of the data chunk that is processed by the
            parallel branch workflow body.
        </outPort>
    </ports>
</knimeNode>
